seed: 1234
amp:
  enabled: true
# torch_home: /path/to/torch
num_workers: 4

dataset:
  name: DG_Dataset
  DG_Dataset:
    use_LMDB: False
    LMDB_root: /path/to/lmdb_database
    train_pos_list1_path: ../data/processed/meta_lists/CASIA_train_pos.txt
    train_neg_list1_path: ../data/processed/meta_lists/CASIA_train_neg.txt
    train_pos_list2_path: ../data/processed/meta_lists/MSU-MFSD_train_pos.txt
    train_neg_list2_path: ../data/processed/meta_lists/MSU-MFSD_train_neg.txt
    train_pos_list3_path:
    train_neg_list3_path:
    val_pos_list_path: ../data/processed/meta_lists/NUAA_train_pos.txt
    val_neg_list_path: ../data/processed/meta_lists/NUAA_train_neg.txt
    test_pos_list_path: ../data/processed/meta_lists/NUAA_test_pos.txt
    test_neg_list_path: ../data/processed/meta_lists/NUAA_test_neg.txt
    img_mode: rgb_hsv
    depth_map: True
    depth_map_size: 32
    crop_face_from_5points: False
    margin: 2
    return_path: True
     # e.g. ['CASIA', 'MSU-MFSD'] — empty = no 
    augment_datasets: ['CASIA', 'MSU-MFSD'] 
    
transform:
  image_size: 256
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  num_segments: 2

model:
  name: Framework
  ckpt_path: 
  resume:
  params:
    in_ch: 6
    mid_ch: 384
    AdapNorm: True
    AdapNorm_attention_flag: 1layer
    model_initial: kaiming
    # switch here: custom_cnn, resnet18, resnet50, vgg16
    backbone: custom_cnn   

loss:
  name: CrossEntropyLoss
  weight: 1.0
  params:
    reduction: mean

loss_2:
  name: MSELoss
  weight: 0.1
  params:
    reduction: mean

loss_3:
  name: EuclideanLoss
  domain_weight: 0.001
  discri_weight: 0.001
  params:
    reduction: mean

optimizer:
  name: Adam
  params:
    lr: 0.001
    weight_decay: 0.00001

scheduler:
  name: StepLR
  params:
    step_size: 20
    gamma: 0.5

train:
  epochs: 50
  batch_size: 4
  accumulation_steps: 8
  print_interval: 10
  metasize: 1
  meta_step_size: 0.001

val:
  batch_size: 4

test:
  batch_size: 4
  record_results: True


wandb:
  project: ANRL
  group: cm2n
  mode: offline
  job_type: train
  id: 
  resume: 
  save_code: True
  name:
  notes:
